# Site settings
title: Shaoyun Wang
general_email: shaoyunwang88@outlook.com
academic_email: shaoyunwang@mail.missouri.edu

description: > # this means to ignore newlines until "baseurl:"
  The universe comprehends me by space and engulfs me like a point; by means of thought, I comprehend it.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://wangshaoyun.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: wangshaoyun
linkedin_username: 
facebook_username: 
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title